language: java
jdk:
  - openjdk8
branches:
  only: master
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install pastebinit
install: true
script:
  - src/test/travis.sh
after_script:
  - pastebinit -i test.log
env:
  matrix:
    - MYSQL_VERSION=5.5
    - MYSQL_VERSION=5.6
    - MYSQL_VERSION=5.7
    - GTID_MODE=1
      MYSQL_VERSION=5.6
    - GTID_MODE=1
      MYSQL_VERSION=5.7
    - MYSQL_VERSION=8.0
addons:
    srcclr: true
